/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// These lines are generated by android-components/automation/application-services-nightly-bump.py
val VERSION = "113.20230320174514"
val CHANNEL = ApplicationServicesChannel.NIGHTLY_STAGING

object ApplicationServicesConfig {
    val version = VERSION
    val channel = CHANNEL
    val groupId = when (channel) {
        ApplicationServicesChannel.RELEASE -> "org.mozilla.appservices"
        ApplicationServicesChannel.STAGING -> "org.mozilla.appservices"
        // Use a different groupid for the nightly channel.  This is a bit of a
        // workaround for the fact that we can't yet upload to the nightly maven
        // repos yet.  Once we can do that, maybe we should use the same groupid in
        // all cases.
        ApplicationServicesChannel.NIGHTLY -> "org.mozilla.appservices.nightly"
        ApplicationServicesChannel.NIGHTLY_STAGING -> "org.mozilla.appservices.nightly"
    }
}

/**
 * Enum for GeckoView release channels.
 *
 * This determines which Maven Repository.  Each channel is uploaded to a separate Maven repository.
 */
enum class ApplicationServicesChannel {
    // Used for official, non-nightly, releases
    RELEASE,
    // Used for nightly releases
    NIGHTLY,
    // Used for preview releases for PRs
    STAGING,
    // Used for nightly releases
    NIGHTLY_STAGING,
}
